#!/bin/bash

options=(
blacklist="tmux, Neovide"
hidpi=on
width=2.0  
active_color="0xffffffff" 
inactive_color="0xff000000"
background_color="0xff000000"
style=round
ax_focus=on
order=below
blur_radius=15.0
)
borders "${options[@]}"
