#!/bin/bash

options=(
blacklist="WezTerm,tmux"
hidpi=on
width=5.0  
active_color="glow(0xfffc5d7c)" 
inactive_color="0xff000000"
background_color="0xff000000"
style=square 
ax_focus=on
order=below
blur_radius=15.0
)
borders "${options[@]}"
