require("items.apple")
require("items.menus")
require("items.spaces")
--require("items.front_app")
require("items.date_time")
require("items.widgets")
require("items.control_center")
require("items.dnd")
require("items.mic")
require("items.display")
require("items.folder")
require("items.date_time")
require("items.lowpowermode")

--sbar.exec("sketchybar --move front_app after item_5")
sbar.exec("sketchybar --move control_center after cal_down")
sbar.exec("sketchybar --move dnd before cal_down")
sbar.exec("sketchybar --move mic after widgets.volume.padding")
sbar.exec("sketchybar --move display after mic")
sbar.exec("sketchybar --move folder after control_center")
sbar.exec("sketchybar --move lowpowermode before widgets.battery")
sbar.exec("sketchybar --move widgets.battery_percentage after lowpowermode")
sbar.exec("sketchybar --move wifi.status before widgets.cpu")
