require("items.apple")
require("items.menus")
require("items.spaces")
require("items.front_app")
require("items.date_time")
require("items.widgets")
require("items.control_center")
require("items.dnd")
require("items.mic")
require("items.display")
require("items.folder")
require("items.calendar")
require("items.date_time")
require("items.music")

sbar.exec("sketchybar --move front_app after item_5")
sbar.exec("sketchybar --move control_center after cal_down")
sbar.exec("sketchybar --move dnd before cal_down")
sbar.exec("sketchybar --move mic after widgets.volume.padding")
sbar.exec("sketchybar --move display after mic")
sbar.exec("sketchybar --move folder after control_center")
sbar.exec("sketchybar --move calendar before control_center")
sbar.exec("sketchybar --move music after control_center")
