require("items.apple")
require("items.menus")
require("items.spaces")
require("items.front_app")
require("items.calendar")
require("items.widgets")
require("items.media")
sbar.exec("sketchybar --move front_app after item_5")
sbar.exec("sketchybar --add item_")
