require("items.apple")
require("items.menus")
require("items.spaces")
require("items.front_app")
require("items.calendar")
require("items.widgets")
-- require("items.media")
require("items.control_center")
require("items.dnd")
require("items.notifications")
require("items.mic")
require("items.display")

sbar.exec("sketchybar --move front_app after item_5")
sbar.exec("sketchybar --move control_center after item_29")
sbar.exec("sketchybar --move dnd before cal_icon")
sbar.exec("sketchybar --move notifications after control_center")
sbar.exec("sketchybar --move mic after widgets.volume.padding")
sbar.exec("sketchybar --move display after mic")
