local icons = {
	loading = "􀖇",
	apple = "􀣺",
	gear = "􀍟",
	cpu = "􀫥",
	gpu = "􀧓",
	dnd_on = "􀆺",
	dnd_off = "􀆹",
	ram = "􀫦",
	music = "􀑪",
	control_center = "􀜊",
	dnd = "􀆺",
	folder = "􀈖",
	notifications = "●",
	vim = "",
	divider = "│",
	audio = { airpods_pro = "􀪷", airpods_max = "􀺹", scarlett = "􂡒", sceptre = "􀢹" },
	menus = { expand = ">", contract = "<" },
	storage = {
		empty = "󰝦",
		full = "󰪥",
		almost_full = "󰪤",
		nearly_full = "󰪣",
		mostly_full = "󰪢",
		half = "󰪡",
		one_third = "󰪠",
		one_quarter = "󰪟",
		low = "󰪞",
	},
	caffeinate = { on = "􀸙", off = "􀸘" },
	display = {
		main_only = "􀟛",
		secondary_only = "􀙗",
		both = "􂤓",
		none = "􀁟",
	},
	weather = {
		day = {
			clear = "",
			partly = "",
			cloud = "",
			fog = "",
			rain = "",
			shower = "",
			snow = "",
			sleet = "",
			ice = "",
			thunder = "",
			snow_thunder = "",
		},
		night = {
			clear = "",
			partly = "",
			cloud = "",
			fog = "",
			rain = "",
			shower = "",
			snow = "",
			sleet = "",
			ice = "",
			thunder = "",
			snow_thunder = "",
		},
	},
	mic = {
		muted = "􀊳",
		on = "􀊱",
	},
	stocks = {
		up = "􀄤",
		down = "􀄥",
		even = "􀂓",
	},
	switch = {
		on = "􁏮",
		off = "􁏯",
	},
	volume = {
		_100 = "􀊩",
		_66 = "􀊧",
		_33 = "􀊥",
		_10 = "􀊡",
		_0 = "􀊣",
	},
	battery = {
		_100 = "􀛨",
		_75 = "􀺸",
		_50 = "􀺶",
		_25 = "􀛩",
		_0 = "􀛪",
		charging = "􀢋",
		lowpower = {
			on = "􀋦",
			off = "􀋥",
		},
	},
	wifi = {
		upload = "􀄨",
		download = "􀄩",
		connected = "􀙇",
		disconnected = "􀙈",
		router = "􁓤",
		vpn = "􀎡",
		ethernet = "􀤆",
		hotspot = "􀉤",
	},
	media = {
		back = "􀊊",
		forward = "􀊌",
		play_pause = "􀊈",
		play = "􀊄",
		pause = "􀊆",
	},
}
return icons
